### ISSUE TITLE
Error Subscribe To Characteristic on iOS

### ISSUE THREAD

**Issue by yuriboeira11tx** [PhilipsHue/flutter_reactive_ble#432] opened 2021-11-01 13:57 UTC
**Describe the bug**
Unfortunately, on iOS devices, the ```subscribeToCharacteristic()``` method is not working, because when using it, an error is raised.

**To Reproduce**
1. Connect to one / many devices using `connectTo()`
2. Read from / write to
3. ```PlatformException(CBATTErrorDomain:10, The attribute could not be found., {NSLocalizedDescription: The attribute could not be found.}, null)```

**Smartphone / tablet**
 - Device: iPhone XS
 - OS: iOS 15
 - Package version: 5.0.1

**Peripheral device**
- Vendor, model: ESP32
- Does it run a custom firmware / software: yes

**Comment by remonh87** [comment] 2021-11-03 18:26
duplicate of #414

**Closed by remonh87** 2021-11-03 18:26 UTC
