### ISSUE TITLE
iOS crashes when turning on Bluetooth switch at app settings(in system Settings)

### ISSUE THREAD

**Issue by ghost** [PhilipsHue/flutter_reactive_ble#286] opened 2021-06-09 03:35 UTC
**Describe the bug**
When user leave app to Settings for granting Bluetooth permission to app, app crashes after turning on Bluetooth switch.

**To Reproduce**
1. turn off Bluetooth switch in app settings.
2. Run app.
3. Listen ble statusStream.
4. Go to app settings at system Settings, turn on Bluetooth switch.
5. App crashes

Error:
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGKILL
    frame #0: 0x00000001bcb6d908 libsystem_kernel.dylib`mach_msg_trap + 8
libsystem_kernel.dylib`mach_msg_trap:
->  0x1bcb6d908 <+8>: ret
libsystem_kernel.dylib`mach_msg_overwrite_trap:
    0x1bcb6d90c <+0>: mov    x16, #-0x20
    0x1bcb6d910 <+4>: svc    #0x80
    0x1bcb6d914 <+8>: ret
Target 0: (Runner) stopped.
Lost connection to device.

**Comment by werediver** [comment] 2021-06-13 13:54
Quick googling points to a similar report: https://github.com/Baseflow/flutter-permission-handler/issues/293

Which mentions this: https://github.com/Baseflow/flutter-permission-handler/issues/368#issuecomment-763854735

Any chance this is your problem? (check the last link)

**Comment by flutterBLE** [comment] 2021-06-15 01:58
Not open app settings programmatically, I press home button and then click system settings icon, find app settings in list, finally turn on/off Bluetooth switch in app settings.
App crashes in my iphone se 2 / iphone 6s plus. If app had bluetooth permission already, turn off Bluetooth switch in app settings still make app crash.

**Comment by ky1vstar** [comment] 2021-11-02 14:29
It's absolutely normal behaviour for iOS to kill application when you change its permissions in Settings app. This is the same for native apps.

**Comment by Taym95** [comment] 2021-11-15 14:10
Please check this response [`Your app is not crashing...`](https://stackoverflow.com/questions/15930708/having-app-restart-itself-when-it-detects-change-to-privacy-settings/15930922#15930922)
 
 I will close this issue for now because it seems like normal IOS behavior.

**Closed by Taym95** 2021-11-15 14:10 UTC

**Comment by octocat-1** [comment] 2021-12-28 10:42
> It's absolutely normal behaviour for iOS to kill application when you change its permissions in Settings app. This is the same for native apps.

Huh? That's rude, what if the user had unsaved data?

**Comment by octocat-1** [comment] 2021-12-30 01:39
This feels like a bug, or an oversight on Apple's side. If it's by design, then it goes against Apple's own advice.
https://developer.apple.com/library/archive/qa/qa1561/_index.html

If setting changes cause an app to close, there should be an alert that communicates that to the user in advance.

**Comment by remonh87** [comment] 2021-12-30 10:47
@octocat-1  I agree it is bad user experience but I think there is little we can do about it. The stack trace is not thrown by our lib but by the OS

**Comment by GordonHuangYong** [comment] 2023-05-30 02:57
> It's absolutely normal behaviour for iOS to kill application when you change its permissions in Settings app. This is the same for native apps.

not really

**Comment by tabekg** [comment] 2024-04-23 10:35
any solutions?
