### ISSUE TITLE
Provides a list of connected devices

### ISSUE THREAD

**Issue by jahnli** [PhilipsHue/flutter_reactive_ble#359] opened 2021-09-13 03:31 UTC
**Describe the solution you'd like**
Provides a list of connected devices

**Comment by jahnli** [comment] 2021-09-13 06:07
If the software is thermally overloaded, the device remains connected and cannot be disconnected,

**Comment by jahnli** [comment] 2021-09-13 06:09
I want to provide an API to get a list of connected devices

**Comment by remonh87** [comment] 2021-09-13 10:50
duplicate of #322 322

**Closed by remonh87** 2021-09-13 10:50 UTC
