### ISSUE TITLE
[Android] Scanning parameters are not set when Firebase is Initialized

### ISSUE THREAD

**Issue by jjchiw** [PhilipsHue/flutter_reactive_ble#196] opened 2021-01-18 11:19 UTC
**Describe the bug**
It's very weird the bug

If I initialize Firebase `await Firebase.initializeApp();` the plugin do not work I added some logs in `ScanDevicesHandler.kt` 

```
D/ABC     (20118): --------------------------------prepareScan
D/ABC     (20118): --------------------------------prepareScan scanParamerters ScanParameters(filter=[], mode=LOW_POWER, locationServiceIsMandatory=true)
D/ABC     (20118): --------------------------------onListen
D/ABC     (20118): --------------------------------onListen scanParameters null
D/ABC     (20118): --------------------------------startDeviceScan
D/ABC     (20118): --------------------------------startDeviceScan scanParameters null
I/flutter (20118): Exception: GenericFailure<ScanFailure>(code: ScanFailure.unknown, message: "Scanning parameters are not set")
```

We can see that the `scanParameters` is null when it start the `onListen` If I remove the line `await Firebase.initializeApp();` everything works as expected

```
D/ABC     (24026): --------------------------------prepareScan
D/ABC     (24026): --------------------------------prepareScan scanParamerters ScanParameters(filter=[], mode=LOW_POWER, locationServiceIsMandatory=true)
D/ABC     (24026): --------------------------------onListen
D/ABC     (24026): --------------------------------onListen scanParameters ScanParameters(filter=[], mode=LOW_POWER, locationServiceIsMandatory=true)
D/ABC     (24026): --------------------------------startDeviceScan
D/ABC     (24026): --------------------------------startDeviceScan scanParameters ScanParameters(filter=[], mode=LOW_POWER, locationServiceIsMandatory=true)
```

**Smartphone / tablet**
 - Device: Xiaomi Mi 8
 - OS: Android 10
 - Package version: 2.7.1

I think it's related with this https://github.com/PhilipsHue/flutter_reactive_ble/issues/195

```
firebase_auth: ^0.18.3
firebase_crashlytics: ^0.2.3
firebase_remote_config: ^0.4.2
firebase_messaging: ^8.0.0-dev.8
firebase_analytics: ^6.2.0
flutter_reactive_ble: ^2.7.1
```

Thanks

**Comment by remonh87** [comment] 2021-01-18 19:14
@jjchiw  it looks like a duplicate of #195 I will close this issue and we will investigate the issue there. Thanks for the clear description though it helps!

**Closed by remonh87** 2021-01-18 19:14 UTC
Labels: Android
