### ISSUE TITLE
How to solve the problem that the device cannot be disconnected after a hot restart

### ISSUE THREAD

**Issue by jahnli** [PhilipsHue/flutter_reactive_ble#375] opened 2021-09-24 06:54 UTC
At present, according to the official example, Connection succeeded, the device is not disconnected after the program hot restart, so that I can not scan the device again, it will always be connected.

**Comment by jahnli** [comment] 2021-09-24 07:00
https://user-images.githubusercontent.com/20943608/134631668-81582b8d-fe40-4072-ba5c-32d9cf68f2b4.mp4

For example, in the video, I tried to connect the 1CD5BC device successfully, but the connection was not disconnected after the hot restart, so the scanning was not possible.

**Comment by jahnli** [comment] 2021-09-24 07:04
https://github.com/PhilipsHue/flutter_reactive_ble/issues/322

**Comment by remonh87** [comment] 2021-09-27 17:10
duplicate of #322

**Closed by remonh87** 2021-09-27 17:10 UTC
